"""Producer Brief Generator — the production spec per approved idea.

An approved Idea is a concept. A Producer Brief is the tight, detailed
production spec that tells the content/video pipeline exactly what to
make: which character, which scene, which data to reference, the exact
spoken script, the exact camera direction, the exact text overlays per
Core-Five segment, and the voice direction.

The Producer Brief is the single source of truth that the content and
video pipelines read. It's generated by Claude from the approved idea
plus the character/scene/data libraries, and it reads like an ad
producer wrote it.
"""

import json
import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from gtm_engine.config import SQLITE_PATH
from gtm_engine.ideas import Idea, IdeaBank
from gtm_engine.scenes import Scene, SceneLibrary
from gtm_engine.data_vault import DataSource, DataVault
from gtm_engine.utils.ai_client import call_claude
from gtm_engine.utils.logger import log_decision

logger = logging.getLogger(__name__)

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS producer_briefs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    idea_id INTEGER NOT NULL,
    character_id TEXT,
    hook_scene_id TEXT,
    tension_scene_id TEXT,
    pivot_scene_id TEXT,
    proof_scene_id TEXT,
    bookend_scene_id TEXT,
    data_source_ids TEXT,
    spoken_script TEXT,
    segments_json TEXT,
    voice_directive TEXT,
    full_brief_md TEXT,
    status TEXT DEFAULT 'draft',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (idea_id) REFERENCES ideas(id)
);
"""


class ProducerBrief(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: int | None = None
    idea_id: int
    character_id: str = "theo"
    hook_scene_id: str = ""
    tension_scene_id: str = ""
    pivot_scene_id: str = ""
    proof_scene_id: str = ""
    bookend_scene_id: str = ""
    data_source_ids: list[int] = Field(default_factory=list)
    spoken_script: str = ""
    segments_json: dict = Field(default_factory=dict)
    voice_directive: str = ""
    full_brief_md: str = ""
    status: str = "draft"
    created_at: str = ""
    updated_at: str = ""


PRODUCER_SYSTEM = """You are a Lead VFX Producer writing a tight, specific production brief
for a 20-second social video in the Quantum Tools Core-Five framework.

Your output is what the content and video pipelines read to make the
actual asset. It must be unambiguous. If a human director picked this
up, they should be able to shoot it without asking questions.

THE CORE-FIVE STRUCTURE (20s = 5 x 4s segments):

=== INVIOLABLE SEGMENT RULES ===

  1. HOOK (0-4s) — THE CHARACTER (Theo) APPEARS HERE
     - Hyper-stylised Theo in one of the locked scenes
     - Animated from hero.png via Veo startFrame
     - This is the ONLY segment where the character appears (besides Bookend)
     - Scroll-stopping opening line

  2. TENSION (4-8s) — NO CHARACTER. DATA/TEXT ONLY.
     - Bold text overlays on dark background (#0a0a0f)
     - OR a data point / statistic filling the screen
     - The uncomfortable truth visualised as typography or numbers
     - NO Theo. NO character. NO person. Pure text/data.

  3. PIVOT (8-12s) — NO CHARACTER. DATA VISUALISATION ONLY.
     - Clean chart, metric dashboard, or product UI screenshot
     - Brand colours: #6c63ff purple, #ffd166 gold on #0a0a0f dark
     - Can be a screen recording of the actual product running
     - NO Theo. NO character. Purely visual evidence.

  4. PROOF (12-16s) — NO CHARACTER. PRODUCT OUTPUT ONLY.
     - Actual product screenshot or screen recording
     - Real data from the Data Vault (PRISM benchmark, Analyst's Edge diagnostic, Atlas trade log)
     - Concrete artefact — real numbers, real output, not a claim
     - NO Theo. NO character. The product speaks for itself.

  5. BOOKEND (16-20s) — THE CHARACTER (Theo) RETURNS
     - EXACT same scene as Hook — same environment, same lighting
     - Theo addresses the viewer directly (helmet turns to camera)
     - Subtle open-palm gesture
     - CTA as text overlay (e.g. "See it run. quantumtools.ai")

=== END SEGMENT RULES ===

If you put the character in Tension, Pivot, or Proof, the brief is WRONG.
Those three segments are: text, data viz, and product output ONLY.

THE CHARACTER:
Theo — The Obsidian Seraph. Male-presenting entity, vantablack suit,
smooth obsidian teardrop helmet, three floating cyan neon halos. No
human facial features. Always animated from a locked hero reference
image via Veo startFrame. ONLY appears in Hook and Bookend.

THE SCENES (you will choose ONE for Hook+Bookend):
Each scene has an id, name, description, and environment prompt. The
operator has provided a list. Pick the one that best fits the idea's
tone. Hook and Bookend MUST use the same scene.

DATA SOURCES:
For Pivot and Proof segments, reference specific data from the Data Vault
whenever possible. If the required data hasn't been added yet, state
explicitly in data_references: {"source_id": null, "needed": "description
of what data is required"}.

YOUR OUTPUT: A JSON object with these fields:

{
  "hook_scene_id": "id of the scene for Hook AND Bookend (same scene)",
  "bookend_scene_id": "MUST match hook_scene_id",
  "spoken_script": "EXACT spoken text, one continuous paragraph, 50-60 words",
  "segments": {
    "hook": {
      "duration_seconds": 4,
      "visual_type": "character_in_scene",
      "visual_direction": "Theo in [scene]. Camera direction. 1-2 sentences.",
      "spoken_text": "exact words spoken during this segment",
      "text_overlay": "on-screen text, max 6 words",
      "transition_out": "how this segment ends (e.g. hard cut to black)"
    },
    "tension": {
      "duration_seconds": 4,
      "visual_type": "text_data_overlay",
      "visual_direction": "Bold white text on #0a0a0f: '[the uncomfortable truth]'. No character. No person.",
      "spoken_text": "exact words",
      "text_overlay": "the main data point or statement",
      "transition_out": "crossfade 0.3s"
    },
    "pivot": {
      "duration_seconds": 4,
      "visual_type": "data_visualisation",
      "visual_direction": "Clean chart/metric on brand dark background. Describe exactly what data is shown.",
      "spoken_text": "exact words",
      "text_overlay": "key metric label",
      "transition_out": "hard cut"
    },
    "proof": {
      "duration_seconds": 4,
      "visual_type": "product_screenshot",
      "visual_direction": "Actual product output — describe what the viewer sees. Name the specific product.",
      "spoken_text": "exact words",
      "text_overlay": "caption pointing to key figure",
      "transition_out": "crossfade 0.3s"
    },
    "bookend": {
      "duration_seconds": 4,
      "visual_type": "character_in_scene",
      "visual_direction": "SAME scene as Hook. Theo turns to camera, open-palm gesture. Exact match.",
      "spoken_text": "exact words — the closing line",
      "text_overlay": "CTA: e.g. 'See it run. quantumtools.ai'",
      "transition_out": "hold 0.5s on final frame"
    }
  },
  "voice_directive": "specific TTS tone direction for this piece",
  "data_references": [
    {"source_id": 1, "used_in_segment": "proof", "how": "display as screenshot"},
    {"source_id": null, "needed": "52-week Atlas performance log", "used_in_segment": "pivot"}
  ],
  "production_notes": "anything else a director needs to know"
}

CONSTRAINTS:
- No shot exceeds 4 seconds
- Hook and Bookend environments MUST match exactly
- Character ONLY in Hook and Bookend — never in Tension, Pivot, Proof
- Tension = text/data overlay on dark background — no scene, no character
- Pivot = data visualisation — no scene, no character
- Proof = product output — no scene, no character
- Spoken script is 50-60 words total
- Forbidden phrases: game-changer, revolutionary, disruptive, innovative,
  cutting-edge, unlock, synergy

Return ONLY the JSON object. No preamble."""


class ProducerBriefLibrary:
    def __init__(self, db_path: Path | None = None):
        self.db_path = db_path or SQLITE_PATH
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _get_conn(self):
        """Get a DB connection — Turso if configured, local SQLite otherwise."""
        from gtm_engine.db.connection import get_connection
        return get_connection(self.db_path)

    def _connect(self) -> sqlite3.Connection:
        conn = self._get_conn()
        conn.row_factory = sqlite3.Row
        return conn

    def _init_schema(self) -> None:
        with self._connect() as conn:
            conn.executescript(SCHEMA_SQL)
            conn.commit()

    def save(self, brief: ProducerBrief) -> int:
        now = datetime.now(timezone.utc).isoformat()
        if not brief.created_at:
            brief.created_at = now
        brief.updated_at = now

        with self._connect() as conn:
            if brief.id:
                conn.execute(
                    """
                    UPDATE producer_briefs SET
                        character_id = ?, hook_scene_id = ?, tension_scene_id = ?,
                        pivot_scene_id = ?, proof_scene_id = ?, bookend_scene_id = ?,
                        data_source_ids = ?, spoken_script = ?, segments_json = ?,
                        voice_directive = ?, full_brief_md = ?, status = ?, updated_at = ?
                    WHERE id = ?
                    """,
                    (
                        brief.character_id, brief.hook_scene_id, brief.tension_scene_id,
                        brief.pivot_scene_id, brief.proof_scene_id, brief.bookend_scene_id,
                        json.dumps(brief.data_source_ids), brief.spoken_script,
                        json.dumps(brief.segments_json), brief.voice_directive,
                        brief.full_brief_md, brief.status, brief.updated_at, brief.id,
                    ),
                )
                conn.commit()
                return brief.id
            else:
                cursor = conn.execute(
                    """
                    INSERT INTO producer_briefs (
                        idea_id, character_id, hook_scene_id, tension_scene_id,
                        pivot_scene_id, proof_scene_id, bookend_scene_id,
                        data_source_ids, spoken_script, segments_json,
                        voice_directive, full_brief_md, status, created_at, updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        brief.idea_id, brief.character_id, brief.hook_scene_id,
                        brief.tension_scene_id, brief.pivot_scene_id, brief.proof_scene_id,
                        brief.bookend_scene_id, json.dumps(brief.data_source_ids),
                        brief.spoken_script, json.dumps(brief.segments_json),
                        brief.voice_directive, brief.full_brief_md, brief.status,
                        brief.created_at, brief.updated_at,
                    ),
                )
                conn.commit()
                return cursor.lastrowid

    def get_for_idea(self, idea_id: int) -> ProducerBrief | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM producer_briefs WHERE idea_id = ? ORDER BY created_at DESC LIMIT 1",
                (idea_id,),
            ).fetchone()
            return self._row_to_brief(row) if row else None

    def list_all(self, status: str | None = None) -> list[ProducerBrief]:
        query = "SELECT * FROM producer_briefs"
        params = []
        if status:
            query += " WHERE status = ?"
            params.append(status)
        query += " ORDER BY created_at DESC"
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
            return [self._row_to_brief(r) for r in rows]

    def _row_to_brief(self, row: sqlite3.Row) -> ProducerBrief:
        return ProducerBrief(
            id=row["id"],
            idea_id=row["idea_id"],
            character_id=row["character_id"] or "theo",
            hook_scene_id=row["hook_scene_id"] or "",
            tension_scene_id=row["tension_scene_id"] or "",
            pivot_scene_id=row["pivot_scene_id"] or "",
            proof_scene_id=row["proof_scene_id"] or "",
            bookend_scene_id=row["bookend_scene_id"] or "",
            data_source_ids=json.loads(row["data_source_ids"] or "[]"),
            spoken_script=row["spoken_script"] or "",
            segments_json=json.loads(row["segments_json"] or "{}"),
            voice_directive=row["voice_directive"] or "",
            full_brief_md=row["full_brief_md"] or "",
            status=row["status"] or "draft",
            created_at=row["created_at"],
            updated_at=row["updated_at"],
        )


def generate_producer_brief(idea_id: int) -> ProducerBrief | None:
    """Generate a detailed producer brief for an approved idea.

    Reads the idea, picks scenes from the Scene Library, pulls any
    referenced data sources, and calls Claude to produce the full
    production spec.
    """
    bank = IdeaBank()
    idea = bank.get(idea_id)
    if not idea:
        logger.error("Idea %d not found", idea_id)
        return None

    scene_lib = SceneLibrary()
    all_scenes = scene_lib.list_all()
    if not all_scenes:
        # Seed if empty
        scene_lib.seed_if_empty()
        all_scenes = scene_lib.list_all()

    scenes_context = "\n".join(
        f"- id: `{s.id}` | {s.name} | best for: {', '.join(s.best_for_segments)} | {s.description[:150]}"
        for s in all_scenes
    )

    # Pull any data sources mentioned by id in the idea notes (optional enrichment)
    vault = DataVault()
    all_data = vault.list_all(verified_only=False)[:20]
    data_context = ""
    if all_data:
        data_context = "\n## AVAILABLE DATA SOURCES\n"
        for d in all_data:
            data_context += f"- id: `{d.id}` | **{d.name}** ({d.source_type}) | {d.description[:150]}\n"

    prompt = (
        f"## IDEA\n\n"
        f"**Title:** {idea.title}\n"
        f"**Hook:** {idea.hook}\n"
        f"**Angle:** {idea.angle}\n"
        f"**Product:** {idea.product or 'umbrella'}\n"
        f"**Target segment:** {idea.target_segment}\n"
        f"**Core-Five segment type (primary):** {idea.segment_type}\n"
        f"**Strategic objective:** {idea.strategic_objective}\n"
        f"**Edginess:** {idea.edginess_score}/10\n"
        f"**Data requirement:** {idea.data_requirement or 'none stated'}\n"
        f"**Notes:** {idea.notes}\n\n"
        f"## AVAILABLE SCENES (pick by id)\n\n{scenes_context}\n"
        f"{data_context}\n\n"
        f"## TASK\n\n"
        f"Produce the full JSON producer brief for this idea. Choose the best "
        f"scenes, write the exact 50-60 word spoken script, specify visual "
        f"direction and text overlays per segment.\n\n"
        f"Return ONLY the JSON."
    )

    try:
        response = call_claude(
            prompt,
            system=PRODUCER_SYSTEM,
            max_tokens=4096,
            temperature=0.5,
        )
    except Exception as e:
        logger.error("Producer brief generation failed for idea %d: %s", idea_id, e)
        return None

    # Parse
    cleaned = response.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[1] if "\n" in cleaned else cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3].rstrip()

    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end == -1:
        logger.error("No JSON object in producer response")
        return None

    try:
        raw = json.loads(cleaned[start : end + 1])
    except json.JSONDecodeError as e:
        logger.error("Producer JSON parse failed: %s", e)
        return None

    # Build the markdown version for display
    full_brief_md = _render_brief_markdown(idea, raw, all_scenes)

    brief = ProducerBrief(
        idea_id=idea_id,
        character_id="theo",
        hook_scene_id=raw.get("hook_scene_id", ""),
        tension_scene_id=raw.get("tension_scene_id", ""),
        pivot_scene_id=raw.get("pivot_scene_id", ""),
        proof_scene_id=raw.get("proof_scene_id", ""),
        bookend_scene_id=raw.get("bookend_scene_id", ""),
        data_source_ids=[
            r.get("source_id") for r in raw.get("data_references", []) if r.get("source_id")
        ],
        spoken_script=raw.get("spoken_script", ""),
        segments_json=raw.get("segments", {}),
        voice_directive=raw.get("voice_directive", ""),
        full_brief_md=full_brief_md,
        status="draft",
    )

    library = ProducerBriefLibrary()
    brief.id = library.save(brief)

    log_decision(
        "producer_brief",
        f"Generated producer brief for idea {idea_id}",
        f"Brief ID: {brief.id}",
    )
    return brief


def _render_brief_markdown(idea: Idea, raw: dict, scenes: list[Scene]) -> str:
    """Turn the JSON producer brief into a readable markdown document."""
    scene_map = {s.id: s for s in scenes}

    # Visual type labels for clarity
    visual_type_labels = {
        "hook": "CHARACTER IN SCENE (Theo)",
        "tension": "TEXT / DATA OVERLAY (no character)",
        "pivot": "DATA VISUALISATION (no character)",
        "proof": "PRODUCT SCREENSHOT (no character)",
        "bookend": "CHARACTER IN SCENE (Theo — same as Hook)",
    }

    lines = [
        f"# Producer Brief",
        f"**Idea #{idea.id}**: {idea.title}",
        "",
        f"*{idea.hook}*",
        "",
        "---",
        "",
        f"## Spoken Script ({len(raw.get('spoken_script', '').split())} words)",
        "",
        f"> {raw.get('spoken_script', '')}",
        "",
        f"**Voice directive:** {raw.get('voice_directive', '')}",
        "",
        "---",
        "",
        "## Core-Five Breakdown",
        "",
    ]

    for seg_id in ["hook", "tension", "pivot", "proof", "bookend"]:
        seg_data = raw.get("segments", {}).get(seg_id, {})
        if not seg_data:
            continue

        # Determine scene (only Hook and Bookend have scenes)
        scene_id = ""
        if seg_id == "hook":
            scene_id = raw.get("hook_scene_id", "")
        elif seg_id == "bookend":
            scene_id = raw.get("bookend_scene_id", "")
        scene = scene_map.get(scene_id) if scene_id else None

        visual_type = seg_data.get("visual_type", visual_type_labels.get(seg_id, ""))
        visual_label = visual_type_labels.get(seg_id, visual_type)

        lines.append(f"### {seg_id.upper()} ({seg_data.get('duration_seconds', 4)}s) — {visual_label}")
        if scene:
            lines.append(f"**Scene:** {scene.name} (`{scene.id}`)")
        lines.append(f"**Visual:** {seg_data.get('visual_direction', '')}")
        lines.append(f"**Spoken:** *\"{seg_data.get('spoken_text', '')}\"*")
        lines.append(f"**Overlay:** `{seg_data.get('text_overlay', '')}`")
        if seg_data.get("transition_out"):
            lines.append(f"**Transition:** {seg_data['transition_out']}")
        lines.append("")

    if raw.get("data_references"):
        lines.append("## Data References")
        for ref in raw["data_references"]:
            if ref.get("source_id"):
                lines.append(f"- Source #{ref['source_id']} used in **{ref.get('used_in_segment')}**: {ref.get('how', '')}")
            elif ref.get("needed"):
                lines.append(f"- **NEEDS DATA**: {ref['needed']} (for **{ref.get('used_in_segment')}** segment)")
        lines.append("")

    if raw.get("production_notes"):
        lines.append("## Production Notes")
        lines.append(raw["production_notes"])

    return "\n".join(lines)
