/**
 * Standardized report generation. Every FLUX report has the same sections in the
 * same order — that is what makes engagements comparable.
 */
import { AUTOMATION, DRIVER, VALUE_CLASS, WASTE } from './frameworks';
import { computeMetrics, prioritize } from './metrics';
import { fmtDuration, fmtMoney, fmtPct } from './format';
import type { Opportunity, OrgDefaults, Process, Project } from '../types';

export function buildProcessReport(
  project: Project,
  process: Process,
  opportunities: Opportunity[],
  org?: OrgDefaults,
): string {
  const m = computeMetrics(process, org);
  const currency = org?.currency ?? 'GBP';
  const opps = prioritize(opportunities);
  const stepById = new Map(process.steps.map((s) => [s.id, s]));

  const lines: string[] = [];
  lines.push(`# FLUX Process Report — ${process.name}`);
  lines.push('');
  lines.push(`**Client:** ${project.client} · **Industry:** ${project.industry} · **Scope:** ${project.scope}`);
  lines.push(`**Generated:** ${new Date().toLocaleString('en-GB')} · **Schema:** FLUX Standard v${process.schemaVersion}`);
  lines.push('');

  // --- Scorecard
  lines.push('## 1. Process Scorecard');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('| --- | --- |');
  lines.push(`| Lead time | ${fmtDuration(m.totalLeadTimeMin)} |`);
  lines.push(`| Touch (process) time | ${fmtDuration(m.totalProcessTimeMin)} |`);
  lines.push(`| Wait time | ${fmtDuration(m.totalWaitTimeMin)} |`);
  lines.push(`| Process Cycle Efficiency (PCE) | ${fmtPct(m.pce, 1)} |`);
  lines.push(`| Rolled %Complete & Accurate | ${fmtPct(m.rolledCompleteAccurate, 1)} |`);
  lines.push(`| Steps (VA / BVA / NVA) | ${m.stepCount} (${m.vaCount} / ${m.bvaCount} / ${m.nvaCount}) |`);
  lines.push(`| Handoffs / Decisions / Rework loops | ${m.handoffCount} / ${m.decisionCount} / ${m.reworkLoopCount} |`);
  lines.push(`| Automation index | ${m.automationIndex}/100 |`);
  if (m.annualCost !== undefined) lines.push(`| Est. annual run-cost | ${fmtMoney(m.annualCost, currency)} |`);
  if (m.annualWasteCost !== undefined) lines.push(`| Est. annual waste (NVA) | ${fmtMoney(m.annualWasteCost, currency)} |`);
  lines.push('');

  // --- SIPOC
  if (process.sipoc) {
    lines.push('## 2. Scope (SIPOC)');
    lines.push('');
    lines.push(`- **Suppliers:** ${process.sipoc.suppliers.join(', ') || '—'}`);
    lines.push(`- **Inputs:** ${process.sipoc.inputs.join(', ') || '—'}`);
    lines.push(`- **Outputs:** ${process.sipoc.outputs.join(', ') || '—'}`);
    lines.push(`- **Customers:** ${process.sipoc.customers.join(', ') || '—'}`);
    lines.push('');
  }

  // --- Map table
  lines.push('## 3. Current-State Map');
  lines.push('');
  lines.push('| # | Step | Type | Actor | System | Value | Touch | Wait | %C&A | Auto |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |');
  for (const s of process.steps) {
    lines.push(
      `| ${s.order} | ${s.name} | ${s.type} | ${s.actor || '—'} | ${s.system || '—'} | ${VALUE_CLASS[s.valueClass].label} | ${s.processTimeMin ?? '—'} | ${s.waitTimeMin ?? '—'} | ${s.pctCompleteAccurate ?? '—'} | ${AUTOMATION[s.automation].label} |`,
    );
  }
  lines.push('');

  // --- Opportunities
  lines.push('## 4. Opportunity Register');
  lines.push('');
  if (!opps.length) {
    lines.push('_No opportunities recorded yet._');
  } else {
    lines.push('| Priority | Opportunity | Driver | Waste | Impact | Effort | Auto | Est. value | Evidence |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const o of opps) {
      const ev = o.stepRefs.map((id) => stepById.get(id)?.order).filter(Boolean).join(', ');
      lines.push(
        `| ${o.priority ?? '—'} | ${o.title}${o.quickWin ? ' ⚡' : ''} | ${DRIVER[o.driver].label} | ${o.waste ? WASTE[o.waste].label : '—'} | ${o.impact} | ${o.effort} | ${AUTOMATION[o.automation].label} | ${o.estAnnualValue ? fmtMoney(o.estAnnualValue, currency) : '—'} | ${ev || '—'} |`,
      );
    }
    lines.push('');
    lines.push('### Recommendations');
    lines.push('');
    for (const o of opps) {
      lines.push(`- **${o.title}** — ${o.recommendation}`);
    }
  }
  lines.push('');

  // --- Future state
  if (process.futureState?.narrative) {
    lines.push('## 5. Future-State Design');
    lines.push('');
    lines.push(process.futureState.narrative);
    lines.push('');
  }

  lines.push('---');
  lines.push('_Generated by FLUX — Execution Intelligence Studio. Benchmarks and estimates require validation against client actuals._');
  return lines.join('\n');
}

export function downloadText(filename: string, text: string, mime = 'text/markdown'): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadJSON(filename: string, data: unknown): void {
  downloadText(filename, JSON.stringify(data, null, 2), 'application/json');
}

export function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 60);
}
