"""Layer 3A — Master Asset Generation.

A master asset is the fully developed idea: insight, argument, narrative,
data point, or story — written to its fullest expression without channel
constraints. It is the source of truth for all derivatives.

Master assets are always generated by Claude.
"""

import json
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path

from gtm_engine.config import DATA_DIR, OUTPUT_DIR
from gtm_engine.discovery.models import GTMBrief
from gtm_engine.strategy.models import GTMStrategy
from gtm_engine.brand import load_brand_standards, benchmark_check
from gtm_engine.utils.ai_client import call_claude
from gtm_engine.utils.file_io import save_json, save_markdown, load_json
from gtm_engine.utils.logger import log_decision

logger = logging.getLogger(__name__)

MASTER_ASSETS_DIR = DATA_DIR / "master_assets"
MASTER_ASSETS_DIR.mkdir(parents=True, exist_ok=True)

MASTER_ASSET_SYSTEM = """You are an elite content strategist generating a master asset
for Quantum Tools. A master asset is the fully developed idea — the insight, the argument,
the narrative — written to its fullest expression.

CONTENT EDGINESS PRINCIPLES (apply ALL of these):
1. SAY THE UNCOMFORTABLE THING — find the market truth everyone knows but nobody says
2. SHOW YOUR WORK — transparency about methodology beats bold claims
3. HAVE A POINT OF VIEW — every piece must contain a clear, arguable perspective
4. PUNCH AT THE CATEGORY — challenge the old way, never name competitors
5. RESPECT THE READER'S INTELLIGENCE — write up, assume sophistication

VOICE: Sharp, transparent, authoritative. Never corporate. Never salesy.
Teach, demonstrate, make them reach for it.

A master asset must contain:
- The core insight or finding
- The uncomfortable truth it surfaces
- The evidence or reasoning behind it
- The point of view the brand takes
- An emotional arc: hook, tension, resolution, soft CTA

Write 800-1500 words. Every sentence must earn its place.
Never use: game-changer, revolutionary, unlock your potential, disruptive, innovative, cutting-edge.

Return a JSON object:
{
    "title": "...",
    "subtitle": "...",
    "body": "full markdown body text",
    "hook": "the opening hook line",
    "uncomfortable_truth": "the core truth this surfaces",
    "point_of_view": "the arguable perspective",
    "target_segments": ["which segments this serves"],
    "edginess_principles_applied": ["which principles"],
    "suggested_derivative_priority": ["ordered list of best derivative formats"]
}"""


def generate_master_asset(
    topic: str,
    brief: GTMBrief,
    strategy: GTMStrategy,
    segment: str = "",
    extra_context: str = "",
) -> dict:
    """Generate a new master asset from a topic and strategic context.

    Returns the master asset dict and saves it to disk.
    """
    asset_id = f"MA-{str(uuid.uuid4())[:6].upper()}"

    prompt_parts = [
        f"TOPIC: {topic}",
        f"TARGET SEGMENT: {segment}" if segment else "",
        f"PRODUCT PORTFOLIO: {brief.umbrella_brand}",
        f"PRODUCTS: {', '.join(p.name for p in brief.products)}",
        f"BRAND TONE: {brief.brand.tone}",
        f"EDGINESS LEVEL: {brief.brand.edginess_level}/10",
    ]

    if strategy.positioning:
        prompt_parts.append(
            f"POSITIONING: {strategy.positioning[0].headline} — {strategy.positioning[0].value_proposition}"
        )

    if strategy.edginess.uncomfortable_truths:
        prompt_parts.append(
            f"UNCOMFORTABLE TRUTHS TO DRAW FROM: {json.dumps(strategy.edginess.uncomfortable_truths[:5])}"
        )

    if extra_context:
        prompt_parts.append(f"\nADDITIONAL CONTEXT: {extra_context}")

    prompt_parts.append("\nGenerate the master asset. Return ONLY valid JSON.")
    prompt = "\n".join(p for p in prompt_parts if p)

    logger.info("Generating master asset: %s", topic[:80])
    response = call_claude(prompt, system=MASTER_ASSET_SYSTEM, max_tokens=6144, temperature=0.8)

    # Parse
    cleaned = response.strip()
    if cleaned.startswith("```"):
        cleaned = cleaned.split("\n", 1)[1] if "\n" in cleaned else cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3].rstrip()
    raw = json.loads(cleaned)

    # Build the master asset record
    asset = {
        "id": asset_id,
        "title": raw.get("title", topic),
        "subtitle": raw.get("subtitle", ""),
        "body": raw.get("body", ""),
        "hook": raw.get("hook", ""),
        "uncomfortable_truth": raw.get("uncomfortable_truth", ""),
        "point_of_view": raw.get("point_of_view", ""),
        "topic": topic,
        "segment": segment,
        "target_segments": raw.get("target_segments", []),
        "edginess_principles_applied": raw.get("edginess_principles_applied", []),
        "suggested_derivative_priority": raw.get("suggested_derivative_priority", []),
        "extra_context": extra_context,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "draft",
        "benchmark_result": None,
    }

    # Run benchmark check
    benchmark = benchmark_check(
        asset["body"], channel="substack", content_type="master_asset"
    )
    asset["benchmark_result"] = benchmark
    if benchmark.get("approved"):
        asset["status"] = "approved"

    # Save
    save_json(asset, MASTER_ASSETS_DIR / f"{asset_id}.json")
    save_markdown(
        f"# {asset['title']}\n\n_{asset['subtitle']}_\n\n{asset['body']}",
        MASTER_ASSETS_DIR / f"{asset_id}.md",
    )

    log_decision(
        "master_asset",
        f"Generated {asset_id}: {asset['title']}",
        f"Benchmark: {'APPROVED' if benchmark.get('approved') else 'NEEDS REVIEW'} "
        f"(score: {benchmark.get('score', 'N/A')})",
        {"asset_id": asset_id},
    )

    logger.info("Master asset %s saved. Status: %s", asset_id, asset["status"])
    return asset


def load_master_asset(asset_id: str) -> dict:
    """Load a master asset by ID."""
    path = MASTER_ASSETS_DIR / f"{asset_id}.json"
    if not path.exists():
        raise FileNotFoundError(f"Master asset {asset_id} not found at {path}")
    return load_json(path)


def list_master_assets() -> list[dict]:
    """List all master assets with their status."""
    assets = []
    for path in sorted(MASTER_ASSETS_DIR.glob("MA-*.json")):
        try:
            data = load_json(path)
            assets.append({
                "id": data.get("id"),
                "title": data.get("title"),
                "status": data.get("status"),
                "created_at": data.get("created_at"),
                "segment": data.get("segment"),
            })
        except Exception:
            pass
    return assets


def import_existing_master_asset(md_path: Path, asset_id: str = "MA-001") -> dict:
    """Import an existing master asset markdown file (like master_asset_001.md).

    Parses the markdown, extracts metadata, and saves as a structured asset.
    """
    content = md_path.read_text(encoding="utf-8")

    # Extract title from first heading
    lines = content.split("\n")
    title = ""
    subtitle = ""
    body_lines = []
    in_derivatives = False

    for line in lines:
        if line.startswith("# MASTER ASSET"):
            continue
        elif line.startswith("## ") and not title:
            title = line.replace("## ", "").strip()
        elif line.startswith("## DERIVATIVES"):
            in_derivatives = True
        elif not in_derivatives and line.startswith("Type:"):
            continue
        elif not in_derivatives and line.startswith("Channel:"):
            continue
        elif not in_derivatives and line.startswith("Segment:"):
            continue
        elif not in_derivatives and line.startswith("Strategic"):
            continue
        elif not in_derivatives and line.startswith("Edginess"):
            continue
        elif not in_derivatives and line.startswith("AI model:"):
            continue
        elif not in_derivatives and line.startswith("Status:"):
            continue
        elif not in_derivatives and line.startswith("Master Asset ID:"):
            continue
        elif not in_derivatives and line.strip() == "---":
            continue
        elif not in_derivatives:
            body_lines.append(line)

    body = "\n".join(body_lines).strip()

    asset = {
        "id": asset_id,
        "title": title or "The Consultancy Death Spiral (And Why White-Label AI Is The Only Exit)",
        "subtitle": "How AI transparency is replacing consulting's black box model",
        "body": body,
        "hook": "Last month, I watched a $50M consultancy lose a client to ChatGPT.",
        "uncomfortable_truth": "Clients are rapidly becoming AI-literate. The old model — black box expertise delivered as finished recommendations — is dying.",
        "point_of_view": "Transparency isn't a weakness. It's the product. The firms going under are the ones still trying to protect the black box.",
        "topic": "Consulting industry disruption by AI and the white-label exit",
        "segment": "All segments — consultants, investors, corporate",
        "target_segments": ["Independent Consultants", "Boutique Advisory", "Corporate Strategy"],
        "edginess_principles_applied": ["say_the_uncomfortable_thing", "show_your_work", "punch_at_the_category"],
        "suggested_derivative_priority": [
            "linkedin_post", "linkedin_carousel", "reel_script",
            "twitter_thread", "email_lifecycle",
        ],
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "approved",
        "benchmark_result": {"approved": True, "score": 9, "verdict": "Quality benchmark — founding asset"},
        "imported_from": str(md_path),
    }

    save_json(asset, MASTER_ASSETS_DIR / f"{asset_id}.json")
    logger.info("Imported master asset %s from %s", asset_id, md_path)
    return asset
