"""Strategy Framework — data models and SQLite storage.

The Content Strategy is the layer above the Idea Bank that defines:
- Audience segments (who you're talking to)
- Content pillars (the recurring themes you own)
- Channel strategy (where you publish, what role each channel plays)
- Funnel stages (what beliefs need to form before conversion)
- Sequencing (what comes first, what comes later)

Every Idea generated downstream is tagged with a pillar_id and a
funnel_stage_id so the dashboard can show distribution, gaps, and
progress against target.
"""

import json
import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from gtm_engine.config import SQLITE_PATH

logger = logging.getLogger(__name__)

SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS content_strategy (
    id INTEGER PRIMARY KEY DEFAULT 1,
    audience_segments TEXT,         -- JSON array
    pillars TEXT,                   -- JSON array
    channels TEXT,                  -- JSON array
    funnel_stages TEXT,             -- JSON array
    sequencing TEXT,                -- JSON array
    capacity_per_week INTEGER DEFAULT 5,
    business_phase TEXT DEFAULT 'pre_launch',
    setup_complete INTEGER DEFAULT 0,
    stages_completed TEXT,          -- JSON array of completed stage ids
    created_at TEXT,
    updated_at TEXT,
    CHECK (id = 1)
);

CREATE TABLE IF NOT EXISTS strategy_feedback (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    tagged_pillar TEXT,
    tagged_channel TEXT,
    tagged_funnel_stage TEXT,
    status TEXT DEFAULT 'active',   -- active | addressed | dismissed
    created_at TEXT NOT NULL,
    addressed_at TEXT
);

CREATE TABLE IF NOT EXISTS rebalance_recommendations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recommendation TEXT NOT NULL,
    rationale TEXT,
    severity TEXT,                  -- low | medium | high
    action_type TEXT,               -- generate | reweight | flag_gap | warn
    target_pillar TEXT,
    target_channel TEXT,
    target_funnel_stage TEXT,
    status TEXT DEFAULT 'pending',  -- pending | accepted | dismissed
    created_at TEXT NOT NULL,
    resolved_at TEXT
);
"""


# --- Universal Pillar Archetypes ---
# Starting vocabulary the user can rename, add to, remove from.

PILLAR_ARCHETYPES = [
    {
        "archetype_id": "problem",
        "default_name": "The Problem",
        "description": "Content that names what's broken about the current way. Surfaces the uncomfortable truth your audience knows but nobody is saying out loud.",
        "why_it_matters": "Until your audience feels the pain, no solution lands. This pillar earns the right to be heard.",
        "default_funnel_stage": "awareness",
        "default_target_percentage": 20.0,
        "example_topics": [
            "Why [current standard practice] is failing",
            "The hidden cost of [common process]",
            "What nobody tells you about [industry norm]",
        ],
    },
    {
        "archetype_id": "solution",
        "default_name": "The Solution",
        "description": "Content that introduces what you do and why it's different. Positions your product or methodology against the category, not against competitors.",
        "why_it_matters": "Once the problem lands, the audience needs to know there's a credible alternative. This is your category claim.",
        "default_funnel_stage": "consideration",
        "default_target_percentage": 25.0,
        "example_topics": [
            "Introducing [your approach]",
            "How [your product] reframes [the problem]",
            "What [your method] makes possible",
        ],
    },
    {
        "archetype_id": "evidence",
        "default_name": "The Evidence",
        "description": "Content that shows the work. Real data, real outputs, real demos. The methodology made visible.",
        "why_it_matters": "Claims are cheap. Sophisticated buyers move when they see the artefact, not the pitch.",
        "default_funnel_stage": "trust",
        "default_target_percentage": 20.0,
        "example_topics": [
            "[Real company/dataset] analysed",
            "Inside the [your methodology]",
            "[Specific output] walkthrough",
        ],
    },
    {
        "archetype_id": "insight",
        "default_name": "The Insight",
        "description": "Original analysis generated by you (or your product) that nobody else is publishing. Demonstrates expertise through use, not claims.",
        "why_it_matters": "Audiences follow people who teach them things they couldn't get elsewhere. This pillar builds authority.",
        "default_funnel_stage": "authority",
        "default_target_percentage": 15.0,
        "example_topics": [
            "Analysis of [recent industry event]",
            "[Surprising pattern] in [your domain]",
            "What [your data] reveals about [audience question]",
        ],
    },
    {
        "archetype_id": "story",
        "default_name": "The Story",
        "description": "Who you are, why you're building this, what you've learned along the way. The human layer.",
        "why_it_matters": "People buy from people. Even B2B audiences want to know the perspective behind the product.",
        "default_funnel_stage": "connection",
        "default_target_percentage": 10.0,
        "example_topics": [
            "Why I'm building [your product]",
            "What I got wrong before [your insight]",
            "Behind the scenes of [your work]",
        ],
    },
    {
        "archetype_id": "enablement",
        "default_name": "The How",
        "description": "Practical content showing how to use your product or apply your methodology. Tutorials, walkthroughs, best practices.",
        "why_it_matters": "Conversion and retention. Audience members who can DO something with your product stay, advocate, and upgrade.",
        "default_funnel_stage": "conversion",
        "default_target_percentage": 10.0,
        "example_topics": [
            "How to [specific use case]",
            "Step-by-step: [feature walkthrough]",
            "Getting the most out of [your product]",
        ],
    },
]


# --- Universal Funnel Stages ---

FUNNEL_STAGES = [
    {
        "id": "awareness",
        "name": "Awareness",
        "description": "I see you. The audience encounters you for the first time and recognises the problem you're talking about.",
        "key_question": "Have you named the problem in a way they recognise?",
    },
    {
        "id": "consideration",
        "name": "Consideration",
        "description": "I get what you do. They understand your offering and how it differs from the alternatives.",
        "key_question": "Have you explained the solution clearly enough that they can imagine using it?",
    },
    {
        "id": "trust",
        "name": "Trust",
        "description": "I believe you can deliver. They've seen evidence — real outputs, real data, real customers — and they trust the claim.",
        "key_question": "Have you shown enough proof that they believe it works?",
    },
    {
        "id": "authority",
        "name": "Authority",
        "description": "I respect your perspective. They follow you for insight they can't get elsewhere.",
        "key_question": "Are you publishing original analysis that demonstrates expertise?",
    },
    {
        "id": "connection",
        "name": "Connection",
        "description": "I feel aligned. They identify with you personally — values, journey, worldview.",
        "key_question": "Do they know who you are and why you're doing this?",
    },
    {
        "id": "conversion",
        "name": "Conversion",
        "description": "I'm ready to act. They're prepared to try, buy, or commit.",
        "key_question": "Have you made the next step obvious and easy?",
    },
    {
        "id": "retention",
        "name": "Retention",
        "description": "I'm staying and bringing others. They're customers and advocates.",
        "key_question": "Are you helping them get more value over time?",
    },
]


# --- Universal Channel Definitions ---

CHANNEL_CATALOGUE = [
    {
        "id": "linkedin",
        "name": "LinkedIn",
        "audience_type": "professional",
        "format_strengths": ["short post", "long-form article", "carousel", "video"],
        "growth_mechanic": "Network-compounding. Consistent posting drives follower growth.",
        "recommended_cadence_low": 2,
        "recommended_cadence_high": 5,
        "typical_pillars": ["problem", "solution", "insight", "story"],
    },
    {
        "id": "twitter",
        "name": "X / Twitter",
        "audience_type": "broad public, niche communities",
        "format_strengths": ["short post", "thread", "quote-tweet"],
        "growth_mechanic": "Reply engagement and retweet velocity. Fast-moving.",
        "recommended_cadence_low": 5,
        "recommended_cadence_high": 14,
        "typical_pillars": ["insight", "story", "problem"],
    },
    {
        "id": "substack",
        "name": "Substack / Newsletter",
        "audience_type": "owned email list",
        "format_strengths": ["long-form essay", "deep dive"],
        "growth_mechanic": "Cross-promotion, recommendations engine, SEO.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 2,
        "typical_pillars": ["evidence", "insight", "problem"],
    },
    {
        "id": "reddit",
        "name": "Reddit",
        "audience_type": "niche communities",
        "format_strengths": ["long-form post", "comment threads"],
        "growth_mechanic": "Algorithmic. Zero audience needed. Value-first or it gets removed.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 3,
        "typical_pillars": ["evidence", "insight", "enablement"],
    },
    {
        "id": "instagram",
        "name": "Instagram / Reels",
        "audience_type": "visual-first consumer and prosumer",
        "format_strengths": ["reel", "carousel", "static post"],
        "growth_mechanic": "Low organic reach without paid boost. Saves are the strongest intent signal.",
        "recommended_cadence_low": 2,
        "recommended_cadence_high": 7,
        "typical_pillars": ["story", "problem", "evidence"],
    },
    {
        "id": "tiktok",
        "name": "TikTok",
        "audience_type": "broad, younger demographic",
        "format_strengths": ["short vertical video"],
        "growth_mechanic": "Algorithmic — can go viral cold. Hook in first 1.5 seconds is critical.",
        "recommended_cadence_low": 3,
        "recommended_cadence_high": 14,
        "typical_pillars": ["problem", "story", "insight"],
    },
    {
        "id": "youtube",
        "name": "YouTube",
        "audience_type": "search-intent driven, longer attention",
        "format_strengths": ["long-form video", "shorts"],
        "growth_mechanic": "SEO + recommendations. Compounds over years.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 3,
        "typical_pillars": ["evidence", "enablement", "insight"],
    },
    {
        "id": "email",
        "name": "Email (lifecycle)",
        "audience_type": "subscribers",
        "format_strengths": ["triggered sequences", "broadcast", "newsletter"],
        "growth_mechanic": "Owned list. Lifecycle sequences outperform broadcasts at every size.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 4,
        "typical_pillars": ["enablement", "solution", "story"],
    },
    {
        "id": "blog_seo",
        "name": "Blog / SEO",
        "audience_type": "search-intent driven",
        "format_strengths": ["long-form article", "pillar pages"],
        "growth_mechanic": "Compounds slowly with search authority.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 4,
        "typical_pillars": ["enablement", "insight", "solution"],
    },
    {
        "id": "podcast",
        "name": "Podcast",
        "audience_type": "long-attention listener",
        "format_strengths": ["interview", "monologue", "panel"],
        "growth_mechanic": "Slow audience growth, very high trust per listener.",
        "recommended_cadence_low": 1,
        "recommended_cadence_high": 4,
        "typical_pillars": ["story", "insight", "evidence"],
    },
]


BUSINESS_PHASES = [
    {
        "id": "pre_launch",
        "name": "Pre-launch",
        "description": "You haven't shipped yet. The job is to establish the worldview and build anticipation.",
        "pillar_weights": {
            "problem": 35.0,
            "story": 25.0,
            "insight": 20.0,
            "solution": 15.0,
            "evidence": 3.0,
            "enablement": 2.0,
        },
    },
    {
        "id": "launch",
        "name": "Launch",
        "description": "You've just shipped or are about to. Push hard on what it is and proof it works.",
        "pillar_weights": {
            "solution": 30.0,
            "evidence": 25.0,
            "problem": 15.0,
            "story": 10.0,
            "insight": 10.0,
            "enablement": 10.0,
        },
    },
    {
        "id": "growth",
        "name": "Growth",
        "description": "Steady-state distribution targeting balanced funnel coverage.",
        "pillar_weights": {
            "solution": 25.0,
            "evidence": 20.0,
            "problem": 20.0,
            "insight": 15.0,
            "story": 10.0,
            "enablement": 10.0,
        },
    },
    {
        "id": "scaling",
        "name": "Scaling",
        "description": "Mature audience. Lean into enablement, retention, and authority content.",
        "pillar_weights": {
            "enablement": 25.0,
            "insight": 25.0,
            "evidence": 20.0,
            "solution": 15.0,
            "story": 10.0,
            "problem": 5.0,
        },
    },
]


# --- Pydantic models ---


class AudienceSegment(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str
    name: str
    description: str = ""
    job_title: str = ""
    pain_points: list[str] = Field(default_factory=list)
    buying_triggers: list[str] = Field(default_factory=list)
    channels_they_use: list[str] = Field(default_factory=list)
    objections: list[str] = Field(default_factory=list)


class Pillar(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str
    name: str
    description: str = ""
    archetype: str = ""
    target_percentage: float = 0.0
    funnel_stage: str = ""
    why_it_matters: str = ""
    example_topics: list[str] = Field(default_factory=list)


class ChannelConfig(BaseModel):
    model_config = ConfigDict(extra="ignore")
    channel_id: str
    enabled: bool = True
    cadence_per_week: int = 1
    primary_pillars: list[str] = Field(default_factory=list)
    audience_segments: list[str] = Field(default_factory=list)
    notes: str = ""


class FunnelStageConfig(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str
    name: str
    description: str = ""
    user_definition: str = ""
    target_percentage: float = 0.0
    pillar_ids: list[str] = Field(default_factory=list)


class SequencingPhase(BaseModel):
    model_config = ConfigDict(extra="ignore")
    phase: str            # pre_launch, launch, growth, scaling
    label: str = ""
    weeks_duration: int = 4
    pillar_weights: dict[str, float] = Field(default_factory=dict)


class StrategyFeedback(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: int | None = None
    text: str
    tagged_pillar: str = ""
    tagged_channel: str = ""
    tagged_funnel_stage: str = ""
    status: str = "active"
    created_at: str = ""
    addressed_at: str = ""


class RebalanceRecommendation(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: int | None = None
    recommendation: str
    rationale: str = ""
    severity: str = "medium"          # low | medium | high
    action_type: str = "flag_gap"     # generate | reweight | flag_gap | warn
    target_pillar: str = ""
    target_channel: str = ""
    target_funnel_stage: str = ""
    status: str = "pending"
    created_at: str = ""
    resolved_at: str = ""


class ContentStrategy(BaseModel):
    model_config = ConfigDict(extra="ignore")
    audience_segments: list[AudienceSegment] = Field(default_factory=list)
    pillars: list[Pillar] = Field(default_factory=list)
    channels: list[ChannelConfig] = Field(default_factory=list)
    funnel_stages: list[FunnelStageConfig] = Field(default_factory=list)
    sequencing: list[SequencingPhase] = Field(default_factory=list)
    capacity_per_week: int = 5
    business_phase: str = "pre_launch"
    setup_complete: bool = False
    stages_completed: list[str] = Field(default_factory=list)
    created_at: str = ""
    updated_at: str = ""


class StrategyStore:
    """SQLite-backed storage for the content strategy."""

    def __init__(self, db_path: Path | None = None):
        self.db_path = db_path or SQLITE_PATH
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_schema()

    def _get_conn(self):
        """Get a DB connection — Turso if configured, local SQLite otherwise."""
        from gtm_engine.db.connection import get_connection
        return get_connection(self.db_path)

    def _connect(self) -> sqlite3.Connection:
        conn = self._get_conn()
        conn.row_factory = sqlite3.Row
        return conn

    def _init_schema(self) -> None:
        with self._connect() as conn:
            conn.executescript(SCHEMA_SQL)
            conn.commit()

    def load(self) -> ContentStrategy:
        with self._connect() as conn:
            row = conn.execute("SELECT * FROM content_strategy WHERE id = 1").fetchone()
            if not row:
                return ContentStrategy()
            return ContentStrategy(
                audience_segments=[AudienceSegment(**s) for s in json.loads(row["audience_segments"] or "[]")],
                pillars=[Pillar(**p) for p in json.loads(row["pillars"] or "[]")],
                channels=[ChannelConfig(**c) for c in json.loads(row["channels"] or "[]")],
                funnel_stages=[FunnelStageConfig(**f) for f in json.loads(row["funnel_stages"] or "[]")],
                sequencing=[SequencingPhase(**s) for s in json.loads(row["sequencing"] or "[]")],
                capacity_per_week=row["capacity_per_week"] or 5,
                business_phase=row["business_phase"] or "pre_launch",
                setup_complete=bool(row["setup_complete"]),
                stages_completed=json.loads(row["stages_completed"] or "[]"),
                created_at=row["created_at"] or "",
                updated_at=row["updated_at"] or "",
            )

    def save(self, strategy: ContentStrategy) -> None:
        now = datetime.now(timezone.utc).isoformat()
        if not strategy.created_at:
            strategy.created_at = now
        strategy.updated_at = now

        with self._connect() as conn:
            conn.execute(
                """
                INSERT OR REPLACE INTO content_strategy (
                    id, audience_segments, pillars, channels, funnel_stages,
                    sequencing, capacity_per_week, business_phase,
                    setup_complete, stages_completed, created_at, updated_at
                ) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    json.dumps([a.model_dump() for a in strategy.audience_segments]),
                    json.dumps([p.model_dump() for p in strategy.pillars]),
                    json.dumps([c.model_dump() for c in strategy.channels]),
                    json.dumps([f.model_dump() for f in strategy.funnel_stages]),
                    json.dumps([s.model_dump() for s in strategy.sequencing]),
                    strategy.capacity_per_week,
                    strategy.business_phase,
                    1 if strategy.setup_complete else 0,
                    json.dumps(strategy.stages_completed),
                    strategy.created_at,
                    strategy.updated_at,
                ),
            )
            conn.commit()

    # --- Feedback ---

    def add_feedback(self, feedback: StrategyFeedback) -> int:
        now = datetime.now(timezone.utc).isoformat()
        if not feedback.created_at:
            feedback.created_at = now
        with self._connect() as conn:
            cursor = conn.execute(
                """
                INSERT INTO strategy_feedback
                  (text, tagged_pillar, tagged_channel, tagged_funnel_stage, status, created_at)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                (
                    feedback.text, feedback.tagged_pillar, feedback.tagged_channel,
                    feedback.tagged_funnel_stage, feedback.status, feedback.created_at,
                ),
            )
            conn.commit()
            return cursor.lastrowid

    def list_feedback(self, status: str | None = None) -> list[StrategyFeedback]:
        query = "SELECT * FROM strategy_feedback"
        params: list = []
        if status:
            query += " WHERE status = ?"
            params.append(status)
        query += " ORDER BY created_at DESC"
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
            return [
                StrategyFeedback(
                    id=r["id"], text=r["text"],
                    tagged_pillar=r["tagged_pillar"] or "",
                    tagged_channel=r["tagged_channel"] or "",
                    tagged_funnel_stage=r["tagged_funnel_stage"] or "",
                    status=r["status"] or "active",
                    created_at=r["created_at"] or "",
                    addressed_at=r["addressed_at"] or "",
                )
                for r in rows
            ]

    def update_feedback_status(self, feedback_id: int, status: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE strategy_feedback SET status = ?, addressed_at = ? WHERE id = ?",
                (status, datetime.now(timezone.utc).isoformat(), feedback_id),
            )
            conn.commit()

    # --- Rebalance recommendations ---

    def add_recommendation(self, rec: RebalanceRecommendation) -> int:
        now = datetime.now(timezone.utc).isoformat()
        if not rec.created_at:
            rec.created_at = now
        with self._connect() as conn:
            cursor = conn.execute(
                """
                INSERT INTO rebalance_recommendations
                  (recommendation, rationale, severity, action_type,
                   target_pillar, target_channel, target_funnel_stage,
                   status, created_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    rec.recommendation, rec.rationale, rec.severity, rec.action_type,
                    rec.target_pillar, rec.target_channel, rec.target_funnel_stage,
                    rec.status, rec.created_at,
                ),
            )
            conn.commit()
            return cursor.lastrowid

    def list_recommendations(self, status: str | None = "pending") -> list[RebalanceRecommendation]:
        query = "SELECT * FROM rebalance_recommendations"
        params: list = []
        if status:
            query += " WHERE status = ?"
            params.append(status)
        query += " ORDER BY severity DESC, created_at DESC"
        with self._connect() as conn:
            rows = conn.execute(query, params).fetchall()
            return [
                RebalanceRecommendation(
                    id=r["id"], recommendation=r["recommendation"],
                    rationale=r["rationale"] or "", severity=r["severity"] or "medium",
                    action_type=r["action_type"] or "flag_gap",
                    target_pillar=r["target_pillar"] or "",
                    target_channel=r["target_channel"] or "",
                    target_funnel_stage=r["target_funnel_stage"] or "",
                    status=r["status"] or "pending",
                    created_at=r["created_at"] or "",
                    resolved_at=r["resolved_at"] or "",
                )
                for r in rows
            ]

    def update_recommendation_status(self, rec_id: int, status: str) -> None:
        with self._connect() as conn:
            conn.execute(
                "UPDATE rebalance_recommendations SET status = ?, resolved_at = ? WHERE id = ?",
                (status, datetime.now(timezone.utc).isoformat(), rec_id),
            )
            conn.commit()


def get_archetype(archetype_id: str) -> dict | None:
    for a in PILLAR_ARCHETYPES:
        if a["archetype_id"] == archetype_id:
            return a
    return None


def get_funnel_stage(stage_id: str) -> dict | None:
    for s in FUNNEL_STAGES:
        if s["id"] == stage_id:
            return s
    return None


def get_channel_spec(channel_id: str) -> dict | None:
    for c in CHANNEL_CATALOGUE:
        if c["id"] == channel_id:
            return c
    return None


def get_business_phase(phase_id: str) -> dict | None:
    for p in BUSINESS_PHASES:
        if p["id"] == phase_id:
            return p
    return None
